# List cameras:  v4l2-ctl --list-devices
# Stable paths:  ls /dev/v4l/by-path/
camera_emotion:
  ros__parameters:
    # video_device: "/dev/v4l/by-path/pci-0000:80:14.0-usb-0:6.2:1.0-video-index0"  # desktop
    video_device: "/dev/video1"  # rk3588 HUE HD Pro camera 1
    camera_info_url: "package://buddy_app/params/vision.camera_info.yaml"
    image_size: [640, 480]
    pixel_format: "YUYV"
    fps: 30

camera_game:
  ros__parameters:
    # video_device: "/dev/v4l/by-path/pci-0000:80:14.0-usb-0:6.1:1.0-video-index0"  # desktop
    video_device: "/dev/video3"  # rk3588 HUE HD Pro camera 2
    camera_info_url: "package://buddy_app/params/vision.camera_info.yaml"
    image_size: [640, 480]
    pixel_format: "YUYV"
    fps: 30
