# Goal
uint8 TRIGGER_VOICE=0
uint8 TRIGGER_EMOTION=1

string session_id
string turn_id
uint8 trigger_type
string user_text
string emotion
float32 emotion_confidence
string[] dialog_history
string system_prompt
sensor_msgs/Image image
---
# Result
string full_response
bool success
string error_message
---
# Feedback
string chunk_text
